-- Re-seed the canonical ranking with the FULL Zach Bryan discography (247 tracks).
--
-- Safe to run: this only replaces the stored track list. Run it in the
-- Supabase SQL editor (SQL Editor -> New query -> paste -> Run).
--
-- Note: this OVERWRITES the current stored order. It's the right thing to
-- run now because the stored list is still the untouched 127-track seed.
-- If you have already spent time reordering, DON'T run this -- just load
-- the page instead; music.html merges any missing catalog tracks onto the
-- bottom of your live order automatically.

update ranking_state
set tracks = $json$
[
  {
    "id": "t1",
    "name": "Condemned - Live",
    "album": "Studio A Recordings (Live)",
    "year": "2021",
    "duration": "2:36",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t2",
    "name": "Flying or Crying - Live",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "3:02",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t3",
    "name": "Condemned",
    "album": "DeAnn",
    "year": "2019",
    "duration": "2:54",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t4",
    "name": "Condemned - Live",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "3:10",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t5",
    "name": "Heading South",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "3:30",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t6",
    "name": "Heading South",
    "album": "Heading South",
    "year": "2019",
    "duration": "2:51",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t7",
    "name": "Heading South - Live",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "3:28",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t8",
    "name": "God Speed - Live",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "4:14",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t9",
    "name": "Something in the Orange - Z&E's Version",
    "album": "Something in the Orange",
    "year": "2022",
    "duration": "4:14",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t10",
    "name": "Heavy Eyes",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:10",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t11",
    "name": "Whiskey Fever",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:32",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t12",
    "name": "Something in the Orange",
    "album": "Something in the Orange",
    "year": "2022",
    "duration": "3:48",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t13",
    "name": "God Speed",
    "album": "DeAnn",
    "year": "2019",
    "duration": "4:13",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t14",
    "name": "Oklahoma City",
    "album": "Oklahoma City",
    "year": "2020",
    "duration": "4:39",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t15",
    "name": "Blue Jean Baby",
    "album": "Blue Jean Baby",
    "year": "2025",
    "duration": "2:12",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t16",
    "name": "Oklahoma City - Live",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "4:31",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t17",
    "name": "Oklahoma City",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "4:00",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t18",
    "name": "Flying or Crying",
    "album": "DeAnn",
    "year": "2019",
    "duration": "2:49",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t19",
    "name": "No Cure",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "2:41",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t20",
    "name": "No Cure - Live",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "2:52",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t21",
    "name": "Oak Island",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:59",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t22",
    "name": "Hey Driver",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "3:47",
    "live": false,
    "feat": "The War and Treaty",
    "guest": null,
    "explicit": false
  },
  {
    "id": "t23",
    "name": "Birmingham",
    "album": "Quiet, Heavy Dreams",
    "year": "2020",
    "duration": "3:26",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t24",
    "name": "Letting Someone Go",
    "album": "DeAnn",
    "year": "2019",
    "duration": "3:59",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t25",
    "name": "This Road I Know",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:24",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n25",
    "name": "South and Pine",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "3:22",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t26",
    "name": "Codeine Pills - Part One",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "3:16",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t27",
    "name": "Madeline",
    "album": "Madeline (feat. Gabriella Rose)",
    "year": "2025",
    "duration": "2:25",
    "live": false,
    "feat": "Gabriella Rose",
    "guest": null,
    "explicit": true
  },
  {
    "id": "t28",
    "name": "From Austin",
    "album": "From Austin",
    "year": "2022",
    "duration": "3:27",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t29",
    "name": "Leaving",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "3:27",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t30",
    "name": "Poems and Closing Time",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "2:41",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t31",
    "name": "Overtime",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "3:10",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t32",
    "name": "Washington Lilacs",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "2:47",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n33",
    "name": "Boys Of Faith",
    "album": "Boys Of Faith",
    "year": "2023",
    "duration": "2:51",
    "live": false,
    "feat": "Bon Iver",
    "guest": null,
    "explicit": true
  },
  {
    "id": "n34",
    "name": "A Song For You",
    "album": "Streets of London",
    "year": "2025",
    "duration": "3:37",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t33",
    "name": "Cold Damn Vampires",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "4:52",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t34",
    "name": "Messed up Kid",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "4:19",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t35",
    "name": "Hell or Highwater - Live",
    "album": "Studio A Recordings (Live)",
    "year": "2021",
    "duration": "2:51",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t36",
    "name": "Loom",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "2:43",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n39",
    "name": "Plastic Cigarette",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "3:06",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n40",
    "name": "Cannonball (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "4:08",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n41",
    "name": "South and Pine (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:39",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n42",
    "name": "Plastic Cigarette (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "3:07",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t37",
    "name": "Doing Fine",
    "album": "DeAnn",
    "year": "2019",
    "duration": "3:04",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n44",
    "name": "Dry Deserts",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "2:31",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t38",
    "name": "Dawns",
    "album": "Dawns (feat. Maggie Rogers)",
    "year": "2023",
    "duration": "4:50",
    "live": false,
    "feat": "Maggie Rogers",
    "guest": null,
    "explicit": true
  },
  {
    "id": "t39",
    "name": "Rattlesnake",
    "album": "Rattlesnake (feat. Zach Bryan)",
    "year": "2025",
    "duration": "4:53",
    "live": false,
    "feat": null,
    "guest": "Jack Van Cleaf",
    "explicit": true
  },
  {
    "id": "t40",
    "name": "Traveling Man",
    "album": "Quiet, Heavy Dreams",
    "year": "2020",
    "duration": "3:17",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t41",
    "name": "Oklahoma Smokeshow",
    "album": "Summertime Blues",
    "year": "2022",
    "duration": "3:31",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n49",
    "name": "Cannonball",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "3:58",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t42",
    "name": "Revival",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "3:41",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t43",
    "name": "A Boy Like You",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "4:48",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t44",
    "name": "Shivers Down Spines",
    "album": "DeAnn",
    "year": "2019",
    "duration": "3:00",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t45",
    "name": "If She Wants a Cowboy",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:12",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t46",
    "name": "Jake's Piano - Long Island",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "5:19",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t47",
    "name": "Open the Gate",
    "album": "Open the Gate",
    "year": "2022",
    "duration": "3:54",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n56",
    "name": "Appetite (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:27",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t48",
    "name": "Open the Gate - Live",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "4:12",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t49",
    "name": "Don't Give up on Me",
    "album": "DeAnn",
    "year": "2019",
    "duration": "3:23",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t50",
    "name": "Summertime's Close",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "3:06",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t51",
    "name": "Driving",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "3:23",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t52",
    "name": "Starved - demo",
    "album": "Starved",
    "year": "2022",
    "duration": "3:44",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t53",
    "name": "Starved",
    "album": "Starved",
    "year": "2022",
    "duration": "4:42",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t54",
    "name": "Starved - Live from Detroit",
    "album": "Starved",
    "year": "2022",
    "duration": "6:15",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t55",
    "name": "Anita - Part Two",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "3:43",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n65",
    "name": "Say Why (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:09",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t56",
    "name": "Better Days",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:32",
    "live": false,
    "feat": "John Mayer",
    "guest": null,
    "explicit": false
  },
  {
    "id": "t57",
    "name": "Hope Again",
    "album": "DeAnn",
    "year": "2019",
    "duration": "3:01",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t58",
    "name": "Let You Down",
    "album": "Quiet, Heavy Dreams",
    "year": "2020",
    "duration": "3:29",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t59",
    "name": "Snow",
    "album": "DeAnn",
    "year": "2019",
    "duration": "2:58",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t60",
    "name": "Tishomingo",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:08",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n71",
    "name": "Say Why",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "2:24",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n72",
    "name": "Nine Ball",
    "album": "Boys Of Faith",
    "year": "2023",
    "duration": "2:50",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t61",
    "name": "East Side of Sorrow",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "3:29",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t62",
    "name": "Motorcycle Drive By",
    "album": "Summertime Blues",
    "year": "2022",
    "duration": "2:41",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t63",
    "name": "Quittin' Time",
    "album": "Summertime Blues",
    "year": "2022",
    "duration": "3:40",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t64",
    "name": "Quittin' Time - Live",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "3:57",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t65",
    "name": "November Air",
    "album": "Quiet, Heavy Dreams",
    "year": "2020",
    "duration": "4:03",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n78",
    "name": "DeAnn's Denim (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:42",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t66",
    "name": "Me and Mine",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "3:09",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t67",
    "name": "From a Lover's Point of View",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "3:04",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n81",
    "name": "Drowning (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:20",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n82",
    "name": "Appetite",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "3:05",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n83",
    "name": "Down, Down, Stream",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "1:59",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n84",
    "name": "Country Roads [Live]",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "3:29",
    "live": true,
    "feat": "Charles Wesley Godwin, Jonathan Peyton & Abigail Peyton",
    "guest": null,
    "explicit": false
  },
  {
    "id": "t68",
    "name": "Pink Skies",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:49",
    "live": false,
    "feat": "Watchhouse",
    "guest": null,
    "explicit": false
  },
  {
    "id": "t69",
    "name": "Dear Miss",
    "album": "Dear Miss",
    "year": "2025",
    "duration": "3:09",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t70",
    "name": "Pink Skies",
    "album": "Pink Skies",
    "year": "2024",
    "duration": "3:14",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t71",
    "name": "Crooked Teeth",
    "album": "Quiet, Heavy Dreams",
    "year": "2020",
    "duration": "3:17",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t72",
    "name": "Fifth of May",
    "album": "The Greatest Day of My Life",
    "year": "2022",
    "duration": "2:58",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t73",
    "name": "Fear and Friday's (Poem)",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "1:47",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t74",
    "name": "Boons",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:05",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t75",
    "name": "High Road",
    "album": "High Road",
    "year": "2024",
    "duration": "3:19",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t76",
    "name": "Lucky Enough (Poem)",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "2:42",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t77",
    "name": "Country Roads",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "3:28",
    "live": true,
    "feat": "Charles Wesley Godwin, Jonathan Peyton, Abigail Peyton",
    "guest": null,
    "explicit": false
  },
  {
    "id": "t78",
    "name": "Late July",
    "album": "Late July",
    "year": "2022",
    "duration": "2:58",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t79",
    "name": "Purple Gas",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:00",
    "live": false,
    "feat": "Noeline Hofmann",
    "guest": null,
    "explicit": true
  },
  {
    "id": "t80",
    "name": "Cold Blooded",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "3:25",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t81",
    "name": "Hopefully",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "3:57",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t82",
    "name": "All the Time",
    "album": "Summertime Blues",
    "year": "2022",
    "duration": "3:19",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t83",
    "name": "Come as You Are",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "4:45",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t84",
    "name": "Sweet DeAnn",
    "album": "DeAnn",
    "year": "2019",
    "duration": "3:24",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t85",
    "name": "Sweet DeAnn - Live",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "3:04",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t86",
    "name": "Old Man",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "4:01",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t87",
    "name": "Moon in Oklahoma",
    "album": "DeAnn",
    "year": "2019",
    "duration": "2:59",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t88",
    "name": "Billy Stay",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "5:16",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t89",
    "name": "Man Thats Never Known You",
    "album": "DeAnn",
    "year": "2019",
    "duration": "3:05",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t90",
    "name": "Memphis; The Blues",
    "album": "Memphis; The Blues (feat. J.R. Carroll)",
    "year": "2025",
    "duration": "3:09",
    "live": false,
    "feat": "J.R. Carroll",
    "guest": null,
    "explicit": true
  },
  {
    "id": "t91",
    "name": "El Dorado",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "3:02",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t92",
    "name": "Someday (Maggie's)",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "4:25",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t93",
    "name": "The Good I'll Do",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:31",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t94",
    "name": "Ninth Cloud",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:23",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t95",
    "name": "Ticking",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "4:02",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t96",
    "name": "Burn, Burn, Burn",
    "album": "Burn, Burn, Burn",
    "year": "2022",
    "duration": "4:28",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t97",
    "name": "Matt and Audie",
    "album": "Summertime Blues",
    "year": "2022",
    "duration": "2:06",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t98",
    "name": "Mine",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "2:58",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t99",
    "name": "Mine Again",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:44",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t100",
    "name": "Summertime Blues",
    "album": "Summertime Blues",
    "year": "2022",
    "duration": "3:01",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t101",
    "name": "Holy Roller",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "3:36",
    "live": false,
    "feat": "Sierra Ferrell",
    "guest": null,
    "explicit": true
  },
  {
    "id": "t102",
    "name": "'68 Fastback",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:13",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t103",
    "name": "Sun to Me",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "2:43",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t104",
    "name": "Quiet, Heavy Dreams",
    "album": "Quiet, Heavy Dreams",
    "year": "2020",
    "duration": "2:54",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t105",
    "name": "Fear and Friday's",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "2:51",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t106",
    "name": "Sober Side of Sorry",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:33",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t107",
    "name": "Highway Boys - Live",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "3:39",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t108",
    "name": "This World's A Giant",
    "album": "This World's A Giant",
    "year": "2024",
    "duration": "3:36",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t109",
    "name": "She's Alright",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:49",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t110",
    "name": "Elisabeth",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "3:19",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t111",
    "name": "Highway Boys",
    "album": "Highway Boys",
    "year": "2022",
    "duration": "3:40",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t112",
    "name": "Happy Instead",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "4:09",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t113",
    "name": "The Outskirts",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:18",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t114",
    "name": "Darling",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:57",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t115",
    "name": "The Greatest Day of My Life",
    "album": "The Greatest Day of My Life",
    "year": "2022",
    "duration": "3:58",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t116",
    "name": "Younger Years",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:25",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t117",
    "name": "Jamie",
    "album": "Summertime Blues",
    "year": "2022",
    "duration": "3:40",
    "live": false,
    "feat": "Charles Wesley Godwin",
    "guest": null,
    "explicit": false
  },
  {
    "id": "t118",
    "name": "Half Grown",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:27",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t119",
    "name": "Twenty So",
    "album": "Summertime Blues",
    "year": "2022",
    "duration": "3:19",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t120",
    "name": "Us Then",
    "album": "Summertime Blues",
    "year": "2022",
    "duration": "2:46",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t121",
    "name": "Morning Time",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:45",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "t122",
    "name": "Blue",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:38",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t123",
    "name": "High Beams",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:20",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t124",
    "name": "Right Now the Best",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:10",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t125",
    "name": "Corinthians (Proctor's)",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "3:51",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t126",
    "name": "You Are My Sunshine",
    "album": "American Heartbreak",
    "year": "2022",
    "duration": "2:57",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "t127",
    "name": "We're Onto Something",
    "album": "We're Onto Something (feat. Zach Bryan)",
    "year": "2025",
    "duration": "3:42",
    "live": false,
    "feat": null,
    "guest": "Kings of Leon",
    "explicit": false
  },
  {
    "id": "n145",
    "name": "DeAnn's Denim",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "2:41",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n146",
    "name": "Bad News",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "3:16",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n147",
    "name": "Slicked Back",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "3:51",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n148",
    "name": "Dry Deserts (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:22",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n149",
    "name": "All Good Things Past (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "3:02",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n150",
    "name": "Santa Fe",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "2:54",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n151",
    "name": "Anyways",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "3:24",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n152",
    "name": "American Nights",
    "album": "The Great American Bar Scene",
    "year": "2025",
    "duration": "3:39",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n153",
    "name": "Runny Eggs",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "3:52",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n154",
    "name": "28",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:53",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n155",
    "name": "Santa Fe (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:32",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n156",
    "name": "Bad News (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:46",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n157",
    "name": "Slicked Back (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:53",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n158",
    "name": "Rivers and Creeks (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "3:08",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n159",
    "name": "Skin",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "2:55",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n160",
    "name": "If They Come Lookin'",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "2:28",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n161",
    "name": "The Great American Bar Scene",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:37",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n162",
    "name": "Drowning",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "3:05",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n163",
    "name": "Rivers and Creeks",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "3:35",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n164",
    "name": "Sandpaper",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:36",
    "live": false,
    "feat": "Bruce Springsteen",
    "guest": null,
    "explicit": false
  },
  {
    "id": "n165",
    "name": "Northern Thunder",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:31",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n166",
    "name": "Skin (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:34",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n167",
    "name": "You Can Still Come Home (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "3:31",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n168",
    "name": "I Remember Everything",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "3:47",
    "live": false,
    "feat": "Kacey Musgraves",
    "guest": null,
    "explicit": false
  },
  {
    "id": "n169",
    "name": "All Good Things Past",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "4:02",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n170",
    "name": "I Remember Everything",
    "album": "I Remember Everything (feat. Kacey Musgraves)",
    "year": "2023",
    "duration": "3:47",
    "live": false,
    "feat": "Kacey Musgraves",
    "guest": null,
    "explicit": false
  },
  {
    "id": "n171",
    "name": "Runny Eggs (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:59",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n172",
    "name": "Anyways (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "1:26",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n173",
    "name": "Bowery",
    "album": "Bowery (feat. Kings of Leon)",
    "year": "2025",
    "duration": "3:36",
    "live": false,
    "feat": "Kings of Leon",
    "guest": null,
    "explicit": true
  },
  {
    "id": "n174",
    "name": "You Can Still Come Home",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "3:41",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n175",
    "name": "Aeroplane",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "2:20",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n176",
    "name": "Always Willin'",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "4:05",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n177",
    "name": "Miles",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "3:31",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n178",
    "name": "With Heaven On Top",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "3:53",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n179",
    "name": "River Washed Hair",
    "album": "Streets of London",
    "year": "2025",
    "duration": "4:22",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n180",
    "name": "The Way Back",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:06",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n181",
    "name": "If They Come Lookin' (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:12",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n182",
    "name": "Sundown Girls",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "2:03",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n183",
    "name": "Aeroplane (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:16",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n184",
    "name": "Camper (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "1:58",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n185",
    "name": "Sundown Girls (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:02",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n186",
    "name": "With Heaven On Top (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:43",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n187",
    "name": "Atlantic City (Live in Jersey)",
    "album": "Atlantic City (Live in Jersey) [feat. Bruce Springsteen and Kings of Leon]",
    "year": "2025",
    "duration": "4:29",
    "live": true,
    "feat": "Bruce Springsteen and Kings of Leon",
    "guest": null,
    "explicit": false
  },
  {
    "id": "n188",
    "name": "Camper",
    "album": "With Heaven On Top",
    "year": "2026",
    "duration": "2:15",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n189",
    "name": "Streets of London",
    "album": "Streets of London",
    "year": "2025",
    "duration": "3:09",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n190",
    "name": "Always Willin' (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "2:47",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n191",
    "name": "Miles (Acoustic)",
    "album": "With Heaven On Top (Acoustic)",
    "year": "2026",
    "duration": "3:25",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n192",
    "name": "Towers",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "2:50",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n193",
    "name": "Tourniquet",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "3:09",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n194",
    "name": "Mechanical Bull",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:29",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n195",
    "name": "Like Ida",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:35",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n196",
    "name": "Bass Boat",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:37",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n197",
    "name": "Funny Man",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "3:17",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n198",
    "name": "Bathwater",
    "album": "The Great American Bar Scene",
    "year": "2024",
    "duration": "1:40",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n199",
    "name": "Spotless",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "2:49",
    "live": false,
    "feat": "The Lumineers",
    "guest": null,
    "explicit": true
  },
  {
    "id": "n200",
    "name": "Tradesman",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "3:08",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n201",
    "name": "Smaller Acts",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "3:07",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n202",
    "name": "Oklahoman Son",
    "album": "Zach Bryan",
    "year": "2023",
    "duration": "4:09",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n203",
    "name": "Codeine Pills, Pt. 1",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "3:16",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n204",
    "name": "Anita, Pt. 2",
    "album": "Elisabeth",
    "year": "2020",
    "duration": "3:44",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n205",
    "name": "The Good I'll Do (Live)",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "3:21",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n206",
    "name": "From Austin (Live)",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2021",
    "duration": "3:16",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n207",
    "name": "Traveling Man (Live)",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2020",
    "duration": "3:40",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n208",
    "name": "'68 Fastback (Live)",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "3:25",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n209",
    "name": "Snow (Live)",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2019",
    "duration": "3:10",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n210",
    "name": "Something in the Orange (Live)",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "4:32",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n211",
    "name": "Oklahoma Smokeshow (Live)",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "3:34",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n212",
    "name": "Billy Stay (Live)",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "4:41",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n213",
    "name": "Jamie [Live]",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "3:33",
    "live": true,
    "feat": "Charles Wesley Godwin",
    "guest": null,
    "explicit": false
  },
  {
    "id": "n214",
    "name": "Heavy Eyes (Live)",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "3:54",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n215",
    "name": "Burn, Burn, Burn (Live)",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2022",
    "duration": "4:14",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n216",
    "name": "November Air (Live)",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2020",
    "duration": "4:26",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n217",
    "name": "Revival (Live)",
    "album": "All My Homies Hate Ticketmaster (Live from Red Rocks)",
    "year": "2020",
    "duration": "11:57",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n218",
    "name": "Sarah's Place",
    "album": "Boys Of Faith",
    "year": "2023",
    "duration": "3:34",
    "live": false,
    "feat": "Noah Kahan",
    "guest": null,
    "explicit": false
  },
  {
    "id": "n219",
    "name": "Deep Satin",
    "album": "Boys Of Faith",
    "year": "2023",
    "duration": "3:31",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n220",
    "name": "Pain, Sweet, Pain",
    "album": "Boys Of Faith",
    "year": "2023",
    "duration": "3:16",
    "live": false,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n221",
    "name": "Overtime (Live From Detroit)",
    "album": "24 (Live)",
    "year": "2023",
    "duration": "4:37",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n222",
    "name": "Open the Gate (Live From Atlanta)",
    "album": "24 (Live)",
    "year": "2022",
    "duration": "4:20",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n223",
    "name": "God Speed (Live From San Antonio)",
    "album": "24 (Live)",
    "year": "2019",
    "duration": "4:25",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n224",
    "name": "The Great American Bar Scene (Live From Philadelphia)",
    "album": "24 (Live)",
    "year": "2024",
    "duration": "3:31",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n225",
    "name": "Fifth of May (Live From Kansas City)",
    "album": "24 (Live)",
    "year": "2022",
    "duration": "4:06",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n226",
    "name": "Tishomingo (Live From Little Rock)",
    "album": "24 (Live)",
    "year": "2022",
    "duration": "3:57",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n227",
    "name": "Oak Island (Live From Dallas)",
    "album": "24 (Live)",
    "year": "2024",
    "duration": "4:22",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n228",
    "name": "Nine Ball (Live From Vancouver)",
    "album": "24 (Live)",
    "year": "2023",
    "duration": "3:34",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n229",
    "name": "'68 Fastback (Live From Tulsa)",
    "album": "24 (Live)",
    "year": "2022",
    "duration": "4:38",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n230",
    "name": "East Side of Sorrow (Live From Nashville)",
    "album": "24 (Live)",
    "year": "2023",
    "duration": "4:24",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n231",
    "name": "28 (Live From Tampa)",
    "album": "24 (Live)",
    "year": "2024",
    "duration": "3:41",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n232",
    "name": "Tourniquet (Live From Oakland)",
    "album": "24 (Live)",
    "year": "2023",
    "duration": "4:13",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n233",
    "name": "Boys Of Faith (Live From Edmonton)",
    "album": "24 (Live)",
    "year": "2023",
    "duration": "3:10",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": true
  },
  {
    "id": "n234",
    "name": "Better Days [Live From Los Angeles]",
    "album": "24 (Live)",
    "year": "2024",
    "duration": "4:22",
    "live": true,
    "feat": "John Mayer",
    "guest": null,
    "explicit": true
  },
  {
    "id": "n235",
    "name": "Oklahoma Smokeshow (Live From Greensboro)",
    "album": "24 (Live)",
    "year": "2022",
    "duration": "3:50",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n236",
    "name": "Dawns [Live From Brooklyn]",
    "album": "24 (Live)",
    "year": "2023",
    "duration": "5:53",
    "live": true,
    "feat": "Maggie Rogers",
    "guest": null,
    "explicit": true
  },
  {
    "id": "n237",
    "name": "Pink Skies (Live From Minneapolis)",
    "album": "24 (Live)",
    "year": "2023",
    "duration": "4:29",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n238",
    "name": "Starved (Live From Sacramento)",
    "album": "24 (Live)",
    "year": "2022",
    "duration": "5:47",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n239",
    "name": "American Nights (Live From Foxborough)",
    "album": "24 (Live)",
    "year": "2024",
    "duration": "3:59",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n240",
    "name": "I Remember Everything [Live From Chicago]",
    "album": "24 (Live)",
    "year": "2023",
    "duration": "4:36",
    "live": true,
    "feat": "Kacey Musgraves",
    "guest": null,
    "explicit": false
  },
  {
    "id": "n241",
    "name": "Hey Driver [Live From Washington, D.C.]",
    "album": "24 (Live)",
    "year": "2024",
    "duration": "5:20",
    "live": true,
    "feat": "The War & Treaty",
    "guest": null,
    "explicit": false
  },
  {
    "id": "n242",
    "name": "Burn, Burn, Burn (Live From Denver)",
    "album": "24 (Live)",
    "year": "2022",
    "duration": "4:35",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n243",
    "name": "Oklahoman Son (Live From Oklahoma City)",
    "album": "24 (Live)",
    "year": "2023",
    "duration": "4:11",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n244",
    "name": "Quittin' Time (Live From Salt Lake City)",
    "album": "24 (Live)",
    "year": "2022",
    "duration": "4:52",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n245",
    "name": "Revival (Live From Knoxville)",
    "album": "24 (Live)",
    "year": "2020",
    "duration": "14:03",
    "live": true,
    "feat": null,
    "guest": null,
    "explicit": false
  },
  {
    "id": "n246",
    "name": "Sarah's Place",
    "album": "Sarah's Place (feat. Noah Kahan)",
    "year": "2023",
    "duration": "3:34",
    "live": false,
    "feat": "Noah Kahan",
    "guest": null,
    "explicit": false
  }
]
$json$::jsonb,
    updated_at = now()
where id = 1;
